version: "3.8"
services:
  frontend:
    build: .
    restart: always
    environment:
      FINANCE_APP_API_HOST: http://raspberrypi.local:8050
    # remove for remote deployment
    ports:
      - "3000:80"